# Generated by Django 4.0.3 on 2023-02-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoPeticion', models.CharField(choices=[('new', 'New'), ('time', 'Time')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('registro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registros.registro')),
                ('autor', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
            },
            bases=('registros.registro',),
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('registro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registros.registro')),
                ('hora', models.TimeField()),
            ],
            options={
                'verbose_name': 'tiempo',
                'verbose_name_plural': 'tiempos',
            },
            bases=('registros.registro',),
        ),
    ]
