# Generated by Django 4.0.3 on 2023-02-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo',
            name='hora',
        ),
        migrations.AddField(
            model_name='tiempo',
            name='ciudad',
            field=models.CharField(default='Santiago de Cali', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiempo',
            name='humedad',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiempo',
            name='temp',
            field=models.IntegerField(default=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipoPeticion',
            field=models.CharField(choices=[('noticia', 'New'), ('tiempo', 'Time')], max_length=10),
        ),
    ]
